RR2 file compressed format (#1194)
* Add code for using rr2 file compressed format in record and replay

* Fix formatting in rr_log.c

* Add RR2 dependencies to docker builds

* Add new rrpack script for RR2 format

* Remove rrunpack script for old rr compressed format

* Update panda_restore to use rrfile_fseek_set for RR2

* Get rr_print to work properly with rr2 code

* Add support for rr2 and old rr replay format

* Revert "Add new rrpack script for RR2 format"

This reverts commit 4d4ee04130c97514050c0655ac004e1176d613e6.

* Revert "Remove rrunpack script for old rr compressed format"

This reverts commit c53407fa4bf59d350e905b1c4157c38438e7e388.

* Add script for packing old recordings in rr2 format

* Add documentation on the new rr2 format and support

* Fix errors in record and replay documentation

* Fix errors found during parallel tests container build

* Remove duplicate packing script for rr2 format

* Update the scissors plugin to handle old and new format

* Update how rr2 filenames are created

* Fix how gargv is copied

* Fix failing qemu test from rr2 modifications

* Update argc copy over to use correct int

* Add support for calling replay without rr2 extension

* Add support for rr2 format in pypanda

* Increase timeout for pypanda panda_expect

* Simplify naming for RR_log fp

* Separate out the loading of snapshot state

* Update comment for RR2

* Capture change in rr2 replay format

* Update snapshot and nondet log print statement for end location

* Make record rr2 creation optional

* Update README to mention command line file created

* Update error in manual related to command line file

* Update scissors to output both rr1 and rr2

* remove rr2 ext from rr_name for recording

* Remove casting replay name automatically to rr2 file if it exists

* Use panda_get_rr_name for replay_name in scissors

* Ignore .rr2 files in git

* Ignore rr.cmd files in git

* Remove code to include cmdline in rr1 recording

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3255,6 +3255,31 @@ if ! compile_prog "$glib_cflags -Werror" "$glib_libs" ; then
 fi
 
 ##########################################
+# libarchive support probe
+if $pkg_config --modversion libarchive > /dev/null 2>&1 ; then
+    archive_libs=`$pkg_config --libs libarchive`
+    LIBS="$archive_libs $LIBS"
+else
+    echo "libarchive is required to compile PANDA"
+    exit 1
+fi
+
+##########################################
+# openssl support probe
+if $pkg_config --modversion libssl > /dev/null 2>&1; then
+    if $pkg_config --modversion libcrypto > /dev/null 2>&1; then
+        ssl_libs=`$pkg_config --libs libssl libcrypto`
+        LIBS="$ssl_libs $LIBS"
+    else
+        echo "libcrypto is required to compile PANDA"
+        exit1
+    fi
+else
+    echo "libssl (openssl) is required to compile PANDA"
+    exit 1
+fi
+
+##########################################
 # SHA command probe for modules
 if test "$modules" = yes; then
     shacmd_probe="sha1sum sha1 shasum"
