Finalize GHA tests

diff --git a/.github/workflows/parallel_taint_unit.yml b/.github/workflows/parallel_taint_unit.yml
--- a/.github/workflows/parallel_taint_unit.yml
+++ b/.github/workflows/parallel_taint_unit.yml
@@ -1,4 +1,4 @@
-name: Taint Unit Test
+name: Taint Unit Tests
 
 on:
   push:
@@ -25,12 +25,12 @@ jobs:
     - name: Download docker/update.sh script from this commit
       run: wget "https://raw.githubusercontent.com/panda-re/panda/${GITHUB_SHA}/panda/docker/update.sh"
 
-    #--mount type=bind,source=/home/panda/regdir/qcows/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2,target=/home/panda/regdir/qcows/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2
     - name: Start container, run update.sh clean build, and run taint unit tests
       run: >-
         docker run --name panda_test_${{ matrix.target }}_${GITHUB_RUN_ID}
         --mount type=bind,source="$(pwd)"/update.sh,target=/update.sh
         --mount type=bind,source=/home/panda/regdir/qcows/wheezy_panda2.qcow2,target=/home/panda/regdir/qcows/wheezy_panda2.qcow2
+        --mount type=bind,source=/home/panda/regdir/qcows/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2,target=/home/panda/regdir/qcows/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2
         --rm -t pandare/panda bash -c
         "cp /update.sh /panda/update.sh;
         chmod u+x /panda/update.sh;
@@ -42,6 +42,6 @@ jobs:
         sed -i '/^\s*$/d' taint2_log;
         if cat taint2_log; then echo 'Taint unit test log found!'; else echo 'Taint unit test log NOT found!' && exit 1; fi;
         echo -e '\nFailures:';
-        if grep 'pass' taint2_log; then echo 'TEST FAILED!' && exit 1; else echo -e 'None.\nTEST PASSED!' && exit 0; fi"
+        if grep 'fail' taint2_log; then echo 'TEST FAILED!' && exit 1; else echo -e 'None.\nTEST PASSED!' && exit 0; fi"
     - name: Cleanup images
       run: docker system prune -af --volumes
