Invert pass condition to see test failure

diff --git a/.github/workflows/taint_unit.yml b/.github/workflows/taint_unit.yml
--- a/.github/workflows/taint_unit.yml
+++ b/.github/workflows/taint_unit.yml
@@ -42,6 +42,6 @@ jobs:
         sed -i '/^\s*$/d' taint2_log;
         if cat taint2_log; then echo 'Taint unit test log found!'; else echo 'Taint unit test log NOT found!' && exit 1; fi;
         echo -e '\nFailures:';
-        if grep 'fail' taint2_log; then echo 'TEST FAILED!' && exit 1; else echo -e 'None.\nTEST PASSED!' && exit 0; fi"
+        if grep 'pass' taint2_log; then echo 'TEST FAILED!' && exit 1; else echo -e 'None.\nTEST PASSED!' && exit 0; fi"
     - name: Cleanup images
       run: docker system prune -af --volumes
